// src/services/connectors/connectorRegistry.js
// Shared registry for the Xeevia evidence connectors.

export const CONNECTOR_DEFINITIONS = {
  x: {
    key: "x",
    name: "X (Twitter)",
    letter: "𝕏",
    color: "#e2e2e2",
    bg: "rgba(226,226,226,0.08)",
    border: "rgba(226,226,226,0.16)",
    desc: "",
    category: "Social",
    live: true,
    connectNote: "",
    evidenceTypes: ["profile", "posts", "replies", "mentions", "followers"],
  },
  facebook: {
    key: "facebook",
    name: "Facebook",
    letter: "f",
    color: "#5b9ef9",
    bg: "rgba(91,158,249,0.08)",
    border: "rgba(91,158,249,0.16)",
    desc: "",
    category: "Social",
    live: true,
    connectNote: "",
    evidenceTypes: ["profile", "posts", "communities"],
  },
  instagram: {
    key: "instagram",
    name: "Instagram",
    letter: "✦",
    color: "#f472b6",
    bg: "rgba(244,114,182,0.08)",
    border: "rgba(244,114,182,0.16)",
    desc: "",
    category: "Visual",
    live: true,
    connectNote: "",
    evidenceTypes: ["profile", "posts", "media"],
  },
  linkedin: {
    key: "linkedin",
    name: "LinkedIn",
    letter: "in",
    color: "#60a5fa",
    bg: "rgba(96,165,250,0.08)",
    border: "rgba(96,165,250,0.16)",
    desc: "",
    category: "Professional",
    live: true,
    connectNote: "",
    evidenceTypes: ["profile", "work_history", "recommendations", "endorsements"],
  },
  google: {
    key: "google",
    name: "Google",
    letter: "G",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    border: "rgba(245,158,11,0.16)",
    desc: "",
    category: "Identity",
    live: true,
    connectNote: "",
    evidenceTypes: ["email", "profile", "verification"],
  },
  apple: {
    key: "apple",
    name: "Apple",
    letter: "",
    color: "#a3a3a3",
    bg: "rgba(163,163,163,0.08)",
    border: "rgba(163,163,163,0.16)",
    desc: "",
    category: "Identity",
    live: true,
    connectNote: "",
    evidenceTypes: ["identity", "device", "verification"],
  },
  github: {
    key: "github",
    name: "GitHub",
    letter: "GH",
    color: "#8b5cf6",
    bg: "rgba(139,92,246,0.08)",
    border: "rgba(139,92,246,0.16)",
    desc: "",
    category: "Developer",
    live: true,
    connectNote: "",
    evidenceTypes: ["repositories", "commits", "projects", "contributions"],
  },
  discord: {
    key: "discord",
    name: "Discord",
    letter: "D",
    color: "#5865f2",
    bg: "rgba(88,101,242,0.08)",
    border: "rgba(88,101,242,0.16)",
    desc: "",
    category: "Community",
    live: true,
    connectNote: "",
    evidenceTypes: ["profile", "communities", "messages"],
  },
  wallet: {
    key: "wallet",
    name: "Wallet",
    letter: "◎",
    color: "#a3e635",
    bg: "rgba(163,230,53,0.08)",
    border: "rgba(163,230,53,0.16)",
    desc: "",
    category: "Finance",
    live: true,
    connectNote: "",
    evidenceTypes: ["wallet", "transactions", "ownership"],
  },
  youtube: {
    key: "youtube",
    name: "YouTube",
    letter: "▶",
    color: "#f87171",
    bg: "rgba(248,113,113,0.07)",
    border: "rgba(248,113,113,0.14)",
    desc: "",
    category: "Video",
    live: false,
    connectNote: "",
    evidenceTypes: ["profile", "videos", "subscribers"],
  },
  tiktok: {
    key: "tiktok",
    name: "TikTok",
    letter: "♪",
    color: "#fb7185",
    bg: "rgba(251,113,133,0.07)",
    border: "rgba(251,113,133,0.14)",
    desc: "",
    category: "Video",
    live: false,
    connectNote: "",
    evidenceTypes: ["profile", "videos", "engagement"],
  },
  threads: {
    key: "threads",
    name: "Threads",
    letter: "@",
    color: "#a78bfa",
    bg: "rgba(167,139,250,0.07)",
    border: "rgba(167,139,250,0.14)",
    desc: "Text-first conversations and creator presence.",
    category: "Social",
    live: false,
    connectNote: "Threads is planned as a social evidence connector.",
    evidenceTypes: ["profile", "posts", "engagement"],
  },
  pinterest: {
    key: "pinterest",
    name: "Pinterest",
    letter: "P",
    color: "#f87171",
    bg: "rgba(248,113,113,0.07)",
    border: "rgba(248,113,113,0.14)",
    desc: "Visual discovery and portfolio-style evidence.",
    category: "Visual",
    live: false,
    connectNote: "Pinterest is planned as a visual evidence connector.",
    evidenceTypes: ["profile", "boards", "pins"],
  },
  reddit: {
    key: "reddit",
    name: "Reddit",
    letter: "R",
    color: "#ff4500",
    bg: "rgba(255,69,0,0.08)",
    border: "rgba(255,69,0,0.16)",
    desc: "Community knowledge and discussion evidence.",
    category: "Community",
    live: false,
    connectNote: "Reddit support is planned for community and knowledge signals.",
    evidenceTypes: ["profile", "posts", "subreddits"],
  },
  telegram: {
    key: "telegram",
    name: "Telegram",
    letter: "✈",
    color: "#2ea6da",
    bg: "rgba(46,166,218,0.08)",
    border: "rgba(46,166,218,0.16)",
    desc: "Community and direct communication evidence.",
    category: "Community",
    live: false,
    connectNote: "Telegram is planned for direct community and channel evidence.",
    evidenceTypes: ["profile", "channels", "messages"],
  },
};

export function getConnectorDefinitions() {
  return CONNECTOR_DEFINITIONS;
}

export function getConnectorByKey(key) {
  return CONNECTOR_DEFINITIONS[key] || null;
}

export function getLiveConnectors() {
  return Object.values(CONNECTOR_DEFINITIONS).filter((item) => item.live);
}
