// src/services/connectors/connectorRegistry.js
// Shared registry for the Xeevia evidence connectors.

export const CONNECTOR_DEFINITIONS = {
  email: {
    key: "email",
    name: "Email",
    letter: "@",
    color: "#60a5fa",
    bg: "rgba(96,165,250,0.08)",
    border: "rgba(96,165,250,0.16)",
    desc: "Verified account email.",
    category: "Identity",
    live: false,
    connectNote: "Your sign-in email is automatically verified here.",
    evidenceTypes: ["email", "verification"],
  },
  x: {
    key: "x",
    name: "X (Twitter)",
    letter: "𝕏",
    color: "#e2e2e2",
    bg: "rgba(226,226,226,0.08)",
    border: "rgba(226,226,226,0.16)",
    desc: "",
    category: "Social",
    live: true,
    connectNote: "",
    evidenceTypes: ["profile", "posts", "replies", "mentions", "followers"],
  },
  facebook: {
    key: "facebook",
    name: "Facebook",
    letter: "f",
    color: "#5b9ef9",
    bg: "rgba(91,158,249,0.08)",
    border: "rgba(91,158,249,0.16)",
    desc: "",
    category: "Social",
    live: true,
    connectionMode: "oauth",
    connectNote: "",
    evidenceTypes: ["profile", "posts", "communities"],
  },
  instagram: {
    key: "instagram",
    name: "Instagram",
    letter: "✦",
    color: "#f472b6",
    bg: "rgba(244,114,182,0.08)",
    border: "rgba(244,114,182,0.16)",
    desc: "",
    category: "Visual",
    live: true,
    connectionMode: "profile_link",
    connectNote: "",
    evidenceTypes: ["profile", "posts", "media"],
  },
  linkedin: {
    key: "linkedin",
    name: "LinkedIn",
    letter: "in",
    color: "#60a5fa",
    bg: "rgba(96,165,250,0.08)",
    border: "rgba(96,165,250,0.16)",
    desc: "",
    category: "Professional",
    live: true,
    connectionMode: "oauth",
    connectNote: "",
    evidenceTypes: ["profile", "work_history", "recommendations", "endorsements"],
  },
  google: {
    key: "google",
    name: "Google",
    letter: "G",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    border: "rgba(245,158,11,0.16)",
    desc: "",
    category: "Identity",
    live: true,
    connectionMode: "oauth",
    connectNote: "",
    evidenceTypes: ["email", "profile", "verification"],
  },
  apple: {
    key: "apple",
    name: "Apple",
    letter: "",
    color: "#a3a3a3",
    bg: "rgba(163,163,163,0.08)",
    border: "rgba(163,163,163,0.16)",
    desc: "",
    category: "Identity",
    live: true,
    connectionMode: "oauth",
    connectNote: "",
    evidenceTypes: ["identity", "device", "verification"],
  },
  github: {
    key: "github",
    name: "GitHub",
    letter: "GH",
    color: "#8b5cf6",
    bg: "rgba(139,92,246,0.08)",
    border: "rgba(139,92,246,0.16)",
    desc: "",
    category: "Developer",
    live: true,
    connectionMode: "oauth",
    connectNote: "",
    evidenceTypes: ["repositories", "commits", "projects", "contributions"],
  },
  discord: {
    key: "discord",
    name: "Discord",
    letter: "D",
    color: "#5865f2",
    bg: "rgba(88,101,242,0.08)",
    border: "rgba(88,101,242,0.16)",
    desc: "",
    category: "Community",
    live: true,
    connectionMode: "oauth",
    connectNote: "",
    evidenceTypes: ["profile", "communities", "messages"],
  },
  wallet: {
    key: "wallet",
    name: "Wallet",
    letter: "◎",
    color: "#a3e635",
    bg: "rgba(163,230,53,0.08)",
    border: "rgba(163,230,53,0.16)",
    desc: "",
    category: "Finance",
    live: true,
    connectionMode: "profile_link",
    connectNote: "",
    evidenceTypes: ["wallet", "transactions", "ownership"],
  },
  youtube: {
    key: "youtube",
    name: "YouTube",
    letter: "▶",
    color: "#f87171",
    bg: "rgba(248,113,113,0.07)",
    border: "rgba(248,113,113,0.14)",
    desc: "",
    category: "Video",
    live: true,
    connectionMode: "profile_link",
    connectNote: "Add your channel link so your public presence is easy to find.",
    evidenceTypes: ["profile", "videos", "subscribers"],
  },
  tiktok: {
    key: "tiktok",
    name: "TikTok",
    letter: "♪",
    color: "#fb7185",
    bg: "rgba(251,113,133,0.07)",
    border: "rgba(251,113,133,0.14)",
    desc: "",
    category: "Video",
    live: true,
    connectionMode: "profile_link",
    connectNote: "Add your public profile link.",
    evidenceTypes: ["profile", "videos", "engagement"],
  },
  threads: {
    key: "threads",
    name: "Threads",
    letter: "@",
    color: "#a78bfa",
    bg: "rgba(167,139,250,0.07)",
    border: "rgba(167,139,250,0.14)",
    desc: "Text-first conversations and creator presence.",
    category: "Social",
    live: true,
    connectionMode: "profile_link",
    connectNote: "Add your public profile link.",
    evidenceTypes: ["profile", "posts", "engagement"],
  },
  pinterest: {
    key: "pinterest",
    name: "Pinterest",
    letter: "P",
    color: "#f87171",
    bg: "rgba(248,113,113,0.07)",
    border: "rgba(248,113,113,0.14)",
    desc: "Visual discovery and portfolio-style evidence.",
    category: "Visual",
    live: true,
    connectionMode: "profile_link",
    connectNote: "Add your public profile or board link.",
    evidenceTypes: ["profile", "boards", "pins"],
  },
  reddit: {
    key: "reddit",
    name: "Reddit",
    letter: "R",
    color: "#ff4500",
    bg: "rgba(255,69,0,0.08)",
    border: "rgba(255,69,0,0.16)",
    desc: "Community knowledge and discussion evidence.",
    category: "Community",
    live: true,
    connectionMode: "profile_link",
    connectNote: "Add your public profile or community link.",
    evidenceTypes: ["profile", "posts", "subreddits"],
  },
  telegram: {
    key: "telegram",
    name: "Telegram",
    letter: "✈",
    color: "#2ea6da",
    bg: "rgba(46,166,218,0.08)",
    border: "rgba(46,166,218,0.16)",
    desc: "Community and direct communication evidence.",
    category: "Community",
    live: true,
    connectionMode: "profile_link",
    connectNote: "Telegram is planned for direct community and channel evidence.",
    evidenceTypes: ["profile", "channels", "messages"],
  },
  twitch: {
    key: "twitch", name: "Twitch", letter: "TW", color: "#a78bfa", bg: "rgba(167,139,250,0.08)", border: "rgba(167,139,250,0.16)", desc: "Live streaming and creator presence.", category: "Streaming", live: true, connectionMode: "profile_link", connectNote: "Add your public channel link.", evidenceTypes: ["profile", "streams", "followers"],
  },
  kick: {
    key: "kick", name: "Kick", letter: "K", color: "#53fc18", bg: "rgba(83,252,24,0.08)", border: "rgba(83,252,24,0.16)", desc: "Live streaming and community presence.", category: "Streaming", live: true, connectionMode: "profile_link", connectNote: "Add your public channel link.", evidenceTypes: ["profile", "streams", "followers"],
  },
  roblox: {
    key: "roblox", name: "Roblox", letter: "R", color: "#e5e7eb", bg: "rgba(229,231,235,0.08)", border: "rgba(229,231,235,0.16)", desc: "Gaming identity and creator profile.", category: "Gaming", live: true, connectionMode: "profile_link", connectNote: "Add your public Roblox profile link.", evidenceTypes: ["profile", "games", "groups"],
  },
  steam: {
    key: "steam", name: "Steam", letter: "S", color: "#66c0f4", bg: "rgba(102,192,244,0.08)", border: "rgba(102,192,244,0.16)", desc: "Gaming profile and library identity.", category: "Gaming", live: true, connectionMode: "profile_link", connectNote: "Add your public Steam profile link.", evidenceTypes: ["profile", "games", "achievements"],
  },
  xbox: {
    key: "xbox", name: "Xbox", letter: "X", color: "#107c10", bg: "rgba(16,124,16,0.08)", border: "rgba(16,124,16,0.16)", desc: "Xbox gamer identity.", category: "Gaming", live: true, connectionMode: "profile_link", connectNote: "Add your public gamer profile link.", evidenceTypes: ["profile", "games", "achievements"],
  },
  playstation: {
    key: "playstation", name: "PlayStation", letter: "PS", color: "#3b82f6", bg: "rgba(59,130,246,0.08)", border: "rgba(59,130,246,0.16)", desc: "PlayStation gamer identity.", category: "Gaming", live: true, connectionMode: "profile_link", connectNote: "Add your public gamer profile link.", evidenceTypes: ["profile", "games", "trophies"],
  },
  epic: {
    key: "epic", name: "Epic Games", letter: "E", color: "#f5f5f5", bg: "rgba(245,245,245,0.08)", border: "rgba(245,245,245,0.16)", desc: "Epic Games player identity.", category: "Gaming", live: true, connectionMode: "profile_link", connectNote: "Add your public profile or creator link.", evidenceTypes: ["profile", "games", "achievements"],
  },
  spotify: {
    key: "spotify", name: "Spotify", letter: "SP", color: "#1ed760", bg: "rgba(30,215,96,0.08)", border: "rgba(30,215,96,0.16)", desc: "Music creator and listening identity.", category: "Audio", live: true, connectionMode: "profile_link", connectNote: "Add your public artist or profile link.", evidenceTypes: ["profile", "artists", "playlists"],
  },
  substack: {
    key: "substack", name: "Substack", letter: "S", color: "#ff6719", bg: "rgba(255,103,25,0.08)", border: "rgba(255,103,25,0.16)", desc: "Newsletter and publishing identity.", category: "Publishing", live: true, connectionMode: "profile_link", connectNote: "Add your public publication link.", evidenceTypes: ["profile", "posts", "publications"],
  },
};

export function getConnectorDefinitions() {
  return CONNECTOR_DEFINITIONS;
}

export function getConnectorByKey(key) {
  return CONNECTOR_DEFINITIONS[key] || null;
}

export function getLiveConnectors() {
  return Object.values(CONNECTOR_DEFINITIONS).filter((item) => item.live);
}
